--
title: "DATA607 - Data Acquisition and Management"
tbl-colwidths: [10,10,20,5,5,5,5,5,5,5]
editor_options: 
  chunk_output_type: console
---

## Meetup Link:

[Click Here to Join the Meetups on Zoom](https://us02web.zoom.us/j/81858708616?pwd=eE9ZGJFco9iicq3BsmANIfWUVLwy0x.1#success)



| Date  | Start Time  | Module    | Slides |  Video  | Main Deliverables |
|--------|--------|------|------|------|
| Jan 27 | 06:45PM | [Introduction to Optimization Theory](../modules/module1) | [Meetup 1 Slides](../meetups/Meetup-1/meetup-1.qmd)  | [Meetup 1 Video](https://youtu.be/Kt3OniP-p1M)  |    |
| Feb 3 | 06:45PM | [Least Squares Optimization](../modules/module2) |    |   | 	[Lab 1](../assignments/labs/Lab1)   |
| Feb 10 | 06:45PM | [Least Squares and Statistics](../modules/module3) |  |  |   |
| Feb 18 | 06:45PM | [Constrained Least Squares and Applications ](../modules/module4) |   |  | [Lab 2](../assignments/labs/Lab2)  |
| Feb 24 | 06:45PM | [Convex Sets](../modules/module5) |  |   |    |
| Mar 3 | 06:45PM | [Convex Sets II ](../modules/module6) |  |   | [Lab 3](../assignments/labs/Lab3.qmd)  |
| Mar 10 | 06:45PM | [Convex Functions](../modules/module7) |  |   |   |
| Mar 17 | 06:45PM | [Convex Functions II](../modules/module8) |  |   | [Lab 4](../assignments/labs/Lab4.qmd)  |
| Mar 24 | 07:0PM | [Convex Optimization Problems](../modules/module9) |  |  |    |
| Mar 31 | 06:45PM | [Data Fitting](../modules/module10) | |  | [Lab 5](../assignments/labs/Lab5.qmd) |
| Apr 7 | 06:45PM | [Applications to Statistics and Machine Learning](../modules/module11) |  |  |   |
| Apr 14 | 06:45PM | [Duality and Classifiers](../modules/module12) |  |  | [Lab 6](../assignments/labs/Lab6)   |
| Apr 21 | | No Meetup (Spring Break) |   |   |   |
| Apr 28 | 06:45PM        | [Gradient Descent and Neural Networks](../modules/module13) | [Lab 7](../assignments/labs/Lab7)  | | |
| May 5  | 06:45PM | [Stochastic Gradient Descent](../modules/module14) |   |    |   |
| May 12  | 06:45PM | [Training Deep Neural Networks](../modules/module15)  | | | [Lab 8](../assignments/Lab8) [Final project](../assignments/project.qmd)  | 

: Course Schedule {.striped .hover}


